### ISSUE TITLE
APIScout with TIBCO BWCE 

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/apiscout#13]
Hi, 

- API Scout 0.2.0
- AKS
- TIBCO BWCE 2.4.1

Wat is the "apiscout/swaggerUrl" value to use when willing to have a REST API by TIBCO BWCE discovered by APIScout ?
TIBCO BWCE swagger ui is usually  "/swagger" ... what if the service has more than one port exposed ?

Thanks,

**Comment by mshahat** [comment]
if i set it to "/swaggerspec", I get the following 

```
2018/12/01 20:04:52 Received ADDED for helloworld
2018/12/01 20:04:52 helloworld should be indexed from /swaggerspec
2018/12/01 20:04:52 error while unmarshaling JSON: invalid character '<' looking for beginning of value
2018/12/01 20:04:52 Service helloworld has been added to API Scout
2018/12/01 20:04:52 Regeneratig Hugo content
```

**Comment by mshahat** [comment]
i believe i understand now that i need to implement /swaggerspec interface in each app
https://tibcosoftware.github.io/apiscout/getting-started/

**Comment by raji-narayanan** [comment]
If this is working now, please close this issue

**Comment by rishikeshpalve** [comment]
@mshahat you don't have to implement the /swaggerspec interface. The swagger spec for a BWCE app can be accessed at '/swagger/swagger.json'

**Comment by mshahat** [comment]
Thanks, @rishikeshpalve ... that got me moving.
I will file other issues for relevant points.
